<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_PROG" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <PROGDIR>
    <NAME>Z4_EXCEPTION_EXAMPLES</NAME>
    <SUBC>1</SUBC>
    <APPL>*</APPL>
    <RSTAT>T</RSTAT>
    <RLOAD>E</RLOAD>
    <FIXPT>X</FIXPT>
    <UCCHECK>X</UCCHECK>
   </PROGDIR>
   <TPOOL>
    <item>
     <ID>I</ID>
     <KEY>001</KEY>
     <ENTRY>Monster is no longer a monster!</ENTRY>
     <LENGTH>62</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>002</KEY>
     <ENTRY>Executing Method FUN_WITH_STATIC_ELECTRICITY</ENTRY>
     <LENGTH>88</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>003</KEY>
     <ENTRY>Exception raised in method FWSE</ENTRY>
     <LENGTH>62</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>004</KEY>
     <ENTRY>Static Exception caught inside of method FWSE</ENTRY>
     <LENGTH>90</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>005</KEY>
     <ENTRY>Executing Method USER_COMMAND</ENTRY>
     <LENGTH>58</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>006</KEY>
     <ENTRY>Function is not available</ENTRY>
     <LENGTH>50</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>007</KEY>
     <ENTRY>User Cancelled Exception has been caught</ENTRY>
     <LENGTH>80</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>008</KEY>
     <ENTRY>Executing Method TRY_CATCH_BLOCK</ENTRY>
     <LENGTH>64</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>009</KEY>
     <ENTRY>Executing Method HEAD_SWAP_OPERATION_WRONG</ENTRY>
     <LENGTH>84</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>010</KEY>
     <ENTRY>Cleanup Block being Executed</ENTRY>
     <LENGTH>56</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>011</KEY>
     <ENTRY>The Monster has No Head!</ENTRY>
     <LENGTH>48</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>012</KEY>
     <ENTRY>Executing Method HEAD_SWAP_OPERATION_RIGHT</ENTRY>
     <LENGTH>84</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>013</KEY>
     <ENTRY>The Monster has No Head! Better do something about that</ENTRY>
     <LENGTH>110</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>014</KEY>
     <ENTRY>Executing Method REPLACE_EVERYTHING</ENTRY>
     <LENGTH>70</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>015</KEY>
     <ENTRY>Exception caught within method REPLACE_EVERYTHING</ENTRY>
     <LENGTH>98</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>016</KEY>
     <ENTRY>Executing Method RETRY</ENTRY>
     <LENGTH>44</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>017</KEY>
     <ENTRY>Raise an Exception!</ENTRY>
     <LENGTH>29</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>018</KEY>
     <ENTRY>Monster STILL has no heads, I am giving up!</ENTRY>
     <LENGTH>86</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>019</KEY>
     <ENTRY>Executing Method RESUMABLE</ENTRY>
     <LENGTH>52</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>020</KEY>
     <ENTRY>The Monster is still a Monster</ENTRY>
     <LENGTH>60</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>021</KEY>
     <ENTRY>Performing generic TRY / CATCH / CLEANUP method business logic</ENTRY>
     <LENGTH>124</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>022</KEY>
     <ENTRY>Raising an exception due to excessive number of wibbly wobbly woos</ENTRY>
     <LENGTH>132</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>023</KEY>
     <ENTRY>Raising an exception due to unusual number of monster components</ENTRY>
     <LENGTH>128</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>024</KEY>
     <ENTRY>Raising an exception with five whole parameters!</ENTRY>
     <LENGTH>96</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>025</KEY>
     <ENTRY>Cleaning up TRY_CATCH_CLEANUP method prior to exception propogation</ENTRY>
     <LENGTH>132</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>026</KEY>
     <ENTRY>Starting Method DO_NOT_KNOW</ENTRY>
     <LENGTH>54</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>027</KEY>
     <ENTRY>The data is rubbish - raise resumable exception</ENTRY>
     <LENGTH>94</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>028</KEY>
     <ENTRY>The data is fine</ENTRY>
     <LENGTH>26</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>029</KEY>
     <ENTRY>The Data has now been repaired - Completing Method DO_NOT_KNOW</ENTRY>
     <LENGTH>124</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>030</KEY>
     <ENTRY>Cleanup</ENTRY>
     <LENGTH>17</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>031</KEY>
     <ENTRY>Static Exception caught outside of method FUN_WITH_STATIC_ELECTRICITY</ENTRY>
     <LENGTH>132</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>032</KEY>
     <ENTRY>Castle Storming Exception has been Caught outside of main method</ENTRY>
     <LENGTH>128</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>033</KEY>
     <ENTRY>Monster is Responding to</ENTRY>
     <LENGTH>48</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>034</KEY>
     <ENTRY>user command</ENTRY>
     <LENGTH>22</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>035</KEY>
     <ENTRY>There are</ENTRY>
     <LENGTH>19</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>036</KEY>
     <ENTRY>wibbly wobbly woos which is terrible!</ENTRY>
     <LENGTH>74</LENGTH>
    </item>
    <item>
     <ID>R</ID>
     <ENTRY>Chapter 04 : Exception Handling</ENTRY>
     <LENGTH>31</LENGTH>
    </item>
   </TPOOL>
  </asx:values>
 </asx:abap>
</abapGit>
